version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../work-place:/var/www/html
    depends_on:
      - php

  php:
    build: ./php
    volumes:
      - ../work-place:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.6
    container_name: docker_db_mere
    ports:
      - 3307:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mere
      MYSQL_USER: root
      MYSQL_PASSWORD: root
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    ports:
      - 8000:80
    volumes:
      - ./phpmyadmin/sessions:/sessions